### ISSUE TITLE
Instagram feed on home page

### ISSUE THREAD

**Issue by sarahmagrish** [sarahmagrish/CFN#6]
Can we use this existing part of the template to do that? 
![screen shot 2015-02-10 at 12 38 22 pm](https://cloud.githubusercontent.com/assets/4765127/6135967/dd7780da-b121-11e4-8328-0ec24bcab07e.png)

You can just use the Ecotrust account for now - attached here as a screen shot
![screen shot 2015-02-10 at 12 43 02 pm](https://cloud.githubusercontent.com/assets/4765127/6136037/6d540e6c-b122-11e4-857f-44bf9d684eb8.png)

**Comment by ghost** [comment]
Take a look at what I did: http://fbb.416.myftpupload.com/

I did not use the Supporters block - like you suggested - it was going to be a lot more work. But let me know what you think, and alternatively, what you liked about the supporters block (the screenshot you posted above) and I can probably add that in pretty easily.

Also, keep in mind we're using the Ecotrust account - so that bit you see above the images is coming from the Ecotrust Instagram account and it will show CFN info, or can also be hidden.

**Comment by ldford** [comment]
I think this is perfect. No need to use supporters block - this looks just like we were thinking. We got a CFN instagram up and running! It's @communityfish - do you need login and pswd?

**Comment by ghost** [comment]
Yeah I’ll need login and password to get it hooked up. Thanks!

—
Jim Krill
jameskrill.com (http://jameskrill.com) | @jimkrill (http://www.twitter.com/jimkrill)

**Comment by ldford** [comment]
Here you go:
Username: communityfish
Password: commf1$h

**Comment by ghost** [comment]
Great! That's all hooked up.
